NapoMVC/Controllers/BackOfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NapoMVC.Controllers
{
    public class BackOfficeController : Controller
    {
        // GET: BackOffice
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Store()
        {
            return View();
        }
        [Authorize]
        public ActionResult Settings()
        {
            return View();
        }
        [Authorize]
        public ActionResult Employees()
        {
            NapoMVC.Models.BLL.UserBLL oUserBLL = new NapoMVC.Models.BLL.UserBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            ViewData["SaleLists"] = oServiceBLL.getSalesListsPerNetwork(_networkId);
            return View();
        }
        [Authorize]
        public ActionResult EmployeeDetails(int EmployeeId)
        {
            return View();
        }
        [Authorize]
        public ActionResult Products()
        {
            return View();
        }
        [Authorize]
        public ActionResult ProductDetails(long ProductId)
        {
            return View();
        }
        [Authorize]
        public ActionResult ServiceTypeDetails(int ServiceTypeId,int NetworkId)
        {
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            NapoMVC.Models.BLL.UserBLL oUserBLL = new NapoMVC.Models.BLL.UserBLL();

            List<ClassRepository.ServiceTypesBase> _lstService = oServiceBLL.getServiceTypesPerNetworkGrid(NetworkId);
            ClassRepository.ServiceTypesBase _tmpLoc = new ClassRepository.ServiceTypesBase();
            _tmpLoc.GUID = "";
            _tmpLoc.Id = 0;
            _tmpLoc.Name = "Nessun padre";
            _tmpLoc.NetworkId = NetworkId;
            _tmpLoc.ParentId = 0;
            _lstService.Add(_tmpLoc);
            ViewData["ServiceTypes"] = _lstService;
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            if (_networkId == NetworkId)
                return View(oServiceBLL.getServiceTypeById(ServiceTypeId,NetworkId));
            else
                return RedirectToAction("AuthError",new { Error = "Mancano i permessi per l'azione richiesta"});
        }
        [Authorize]
        public ActionResult UpServiceTypeDetails(ClassRepository.ServiceTypesBase oUp)
        {
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            List<ClassRepository.ServiceTypesBase> _lstService = oServiceBLL.getServiceTypesPerNetworkGrid(oUp.NetworkId);
            ClassRepository.ServiceTypesBase _tmpLoc = new ClassRepository.ServiceTypesBase();
            _tmpLoc.GUID = "";
            _tmpLoc.Id = 0;
            _tmpLoc.Name = "Nessun padre";
            _tmpLoc.NetworkId = oUp.NetworkId;
            _tmpLoc.ParentId = 0;
            _lstService.Add(_tmpLoc);
            ViewData["ServiceTypes"] = _lstService;
            NapoMVC.Models.BLL.UserBLL oUserBLL = new NapoMVC.Models.BLL.UserBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            ViewBag.ins = "";
            ClassRepository.ResponseStatus oStatus = new ClassRepository.ResponseStatus();
            if (_networkId == oUp.NetworkId)
                return View("ServiceTypeDetails", oServiceBLL.setServiceType(oUp, out oStatus) );
            else
                return RedirectToAction("AuthError", new { Error = "Mancano i permessi per l'azione richiesta" });
        }

        [Authorize]
        public ActionResult AuthError(string Error)
        {
            return View(Error);
        }

        [Authorize]
        public ActionResult Services()
        {
            NapoMVC.Models.BLL.UserBLL oUserBLL = new NapoMVC.Models.BLL.UserBLL();
            Models.BLL.VATBLL oVATBLL = new Models.BLL.VATBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            ViewData["SaleLists"] = oServiceBLL.getSalesListsPerNetwork(_networkId);
            ViewData["VAT"] = oVATBLL.getVatPerNetwork(_networkId);
            return View();
        }
        [Authorize]
        public ActionResult ServiceDetails(long ServiceId,int NetworkId)
        {
            return View();
        }
        [Authorize]
        public ActionResult Customers()
        {
            return View();
        }
        [Authorize]
        public ActionResult CustomerDetails(long CustomerId)
        {
            return View();
        }
        [Authorize]
        public ActionResult Cabins()
        {
            return View();
        }
        [Authorize]
        public ActionResult CabinDetails(long CabinId)
        {
            return View();
        }
        [Authorize]
        public ActionResult Suppliers()
        {
            return View();
        }
        [Authorize]
        public ActionResult SupplierDetails(long SupplierId)
        {
            return View();
        }
        [Authorize]
        public ActionResult ServiceTypes()
        {
            NapoMVC.Models.BLL.UserBLL oUserBLL = new NapoMVC.Models.BLL.UserBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            ViewData["ServiceTypes"] = oServiceBLL.getServiceTypesPerNetworkGrid(_networkId);
            return View();
        }
        
        [Authorize]
        public ActionResult GeneralSettings()
        {
            return View();
        }
        [Authorize]
        public ActionResult Header()
        {
            return PartialView("_partialHeader");
        }
        public ActionResult ModalTypeinsert()
        {
            NapoMVC.Models.BLL.UserBLL oUserBLL = new NapoMVC.Models.BLL.UserBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            return PartialView("~/Views/Shared/Partial/_PartialModalTypeAdd.cshtml", _networkId);
        }
    }
}

NapoMVC/Controllers/CRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json;
using ClassRepository;
using NapoMVC.Models.BLL;
namespace NapoMVC.Controllers
{
    public class CRUDController : Controller
    {
        #region Employee
        [Authorize]
        public ActionResult Employees_Read(int NetworkId, [DataSourceRequest] DataSourceRequest request)
        {
            EmployeeBLL oBLL = new Models.BLL.EmployeeBLL();
            return Json(oBLL.getEmployeesInNetwork(NetworkId).ToDataSourceResult(request));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize]
        public ActionResult Employee_Update([DataSourceRequest] DataSourceRequest request, Employee EmployeeUp)
        {
            if (EmployeeUp != null && ModelState.IsValid)
            {
                EmployeeBLL oBLL = new Models.BLL.EmployeeBLL();
                oBLL.EmployeeUpdate(EmployeeUp);
            }
            return Json(new[] { EmployeeUp }.ToDataSourceResult(request, ModelState));
        }

        [Authorize]
        public ActionResult setEmployee(string JsonData)
        {
            EmployeeAPI oRet = new EmployeeAPI();
            Employee _employee = JsonConvert.DeserializeObject<Employee>(JsonData);
            EmployeeBLL oServiceBLL = new EmployeeBLL();
            UserBLL oUserBLL = new UserBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            if (_networkId == _employee.NetworkId)
            {
                ResponseStatus _status = new ResponseStatus();
                oRet = oServiceBLL.setEmployee(_employee);
            }
            else
            {
                oRet.Status.Status = -100;
                oRet.Status.Error = "Errore id Network";
            }
            return Json(oRet, JsonRequestBehavior.AllowGet);
        }


        [Authorize]
        public ActionResult getUsersNonInemployee(int NetworkId)
        {
            UserBLL oBLL = new Models.BLL.UserBLL();
            List<UserNetwork> _lst = oBLL.getUserNetworkNonEmployee(NetworkId);
            return Json(_lst, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult getUsersNonInemployeeWithSelect(int NetworkId,int UserId)
        {
            UserBLL oBLL = new Models.BLL.UserBLL();
            List<UserNetwork> _lst = oBLL.getUserNetworkNonEmployee(NetworkId,UserId);
            return Json(_lst, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region Product
        [Authorize]
        public ActionResult Product_Read(int NetworkId, [DataSourceRequest] DataSourceRequest request)
        {
            ProductBLL oBLL = new Models.BLL.ProductBLL();
            return Json(oBLL.getProductsInNetwork(NetworkId).ToDataSourceResult(request));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize]
        public ActionResult Product_Update([DataSourceRequest] DataSourceRequest request, Product ProductUp)
        {
            if (ProductUp != null && ModelState.IsValid)
            {
                ProductBLL oBLL = new Models.BLL.ProductBLL();
                oBLL.ProductUpdate(ProductUp);
            }
            return Json(new[] { ProductUp }.ToDataSourceResult(request, ModelState));
        }
        #endregion

        #region Service
        [Authorize]
        public ActionResult Service_Read(int NetworkId, [DataSourceRequest] DataSourceRequest request)
        {
            ServiceBLL oBLL = new Models.BLL.ServiceBLL();
            return Json(oBLL.getServicesGridInNetwork(NetworkId).ToDataSourceResult(request));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize]
        public ActionResult Service_Update([DataSourceRequest] DataSourceRequest request, Service ServiceUp)
        {
            if (ServiceUp != null && ModelState.IsValid)
            {
                ServiceBLL oBLL = new Models.BLL.ServiceBLL();
                oBLL.ServiceUpdate(ServiceUp);
            }
            return Json(new[] { ServiceUp }.ToDataSourceResult(request, ModelState));
        }
        [Authorize]
        public ActionResult setService(string JsonData)
        {
            ServiceBaseResponse oRet = new ServiceBaseResponse();
            Service _serviceType = JsonConvert.DeserializeObject<Service>(JsonData);
            //_serviceType.ServiceType1.Id = _serviceType.type1;
            //_serviceType.ServiceType2.Id = _serviceType.type2;
            _serviceType.ServiceType = new ServiceTypeComplex();
            _serviceType.ServiceType.ServiceTypeChild.Id = _serviceType.type2;
            _serviceType.ServiceType.ServiceTypeParent.Id = _serviceType.type1;
            ServiceBLL oServiceBLL = new ServiceBLL();
            UserBLL oUserBLL = new UserBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            if (_networkId == _serviceType.NetworkId)
            {
                ResponseStatus _status = new ResponseStatus();
                _serviceType = oServiceBLL.setService(_serviceType, out _status);
                oRet.Status = _status;
                oRet.Type = _serviceType;
            }
            else
            {
                oRet.Status.Status = -100;
                oRet.Status.Error = "Errore id Network";
            }
            return Json(oRet, JsonRequestBehavior.AllowGet);
        }


        [Authorize]
        public ActionResult ServiceTypes_Read(int NetworkId, [DataSourceRequest] DataSourceRequest request)
        {
            ServiceBLL oBLL = new ServiceBLL();
            return Json(oBLL.getServiceTypesPerNetworkGrid(NetworkId).ToDataSourceResult(request));
        }
        [Authorize]
        public ActionResult setServiceType(string JsonData)
        {
            ServiceTypeBaseResponse oRet = new ServiceTypeBaseResponse();
            ServiceTypesBase _serviceType = JsonConvert.DeserializeObject<ServiceTypesBase>(JsonData);
            ServiceBLL oServiceBLL = new ServiceBLL();
            UserBLL oUserBLL = new UserBLL();
            int _networkId = oUserBLL.getUserNetwork(User.Identity.Name);
            if (_networkId == _serviceType.NetworkId)
            {
                ResponseStatus _status = new ResponseStatus();
                _serviceType = oServiceBLL.setServiceType(_serviceType, out _status);
                oRet.Status = _status;
                oRet.Type = _serviceType;
            }
            else
            {
                oRet.Status.Status = -100;
                oRet.Status.Error = "Errore id Network";
            }
            return Json(oRet, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public ActionResult getParentServices(int NetworkId)
        {
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            List<ServiceTypesBase> _lst = oServiceBLL.getServiceTypesPerNetworkGrid(NetworkId).Where(x=>x.ParentId==x.Id).ToList();
            return Json(_lst, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getServices(int NetworkId)
        {
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            List<ServiceTypesBase> _lst = oServiceBLL.getServiceTypesPerNetworkGrid(NetworkId);
            return Json(_lst, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getChildrenServices(int NetworkId,int ParentId)
        {
            Models.BLL.ServiceBLL oServiceBLL = new Models.BLL.ServiceBLL();
            List<ServiceTypesBase> _lst = oServiceBLL.getServiceTypesPerNetworkGrid(NetworkId);
            var q = from x in _lst where x.ParentId == ParentId && x.Id != x.ParentId select x;
            _lst = q.ToList();
            return Json(_lst, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Customer
        [Authorize]
        public ActionResult Customer_Read(int NetworkId, [DataSourceRequest] DataSourceRequest request)
        {
            CustomerBLL oBLL = new Models.BLL.CustomerBLL();
            return Json(oBLL.getCustomersInNetwork(NetworkId).ToDataSourceResult(request));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize]
        public ActionResult Customer_Update([DataSourceRequest] DataSourceRequest request, Customer CustomerUp)
        {
            if (CustomerUp != null && ModelState.IsValid)
            {
                CustomerBLL oBLL = new Models.BLL.CustomerBLL();
                oBLL.CustomerUpdate(CustomerUp);
            }
            return Json(new[] { CustomerUp }.ToDataSourceResult(request, ModelState));
        }
        #endregion
        #region Cabin
        [Authorize]
        public ActionResult Cabins_Read(int NetworkId, [DataSourceRequest] DataSourceRequest request)
        {
            CabinBLL oBLL = new Models.BLL.CabinBLL();
            return Json(oBLL.getCabinsInNetwork(NetworkId).ToDataSourceResult(request));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize]
        public ActionResult Cabin_Update([DataSourceRequest] DataSourceRequest request, Cabin CabinUp)
        {
            if (CabinUp != null && ModelState.IsValid)
            {
                CabinBLL oBLL = new Models.BLL.CabinBLL();
                oBLL.CabinUpdate(CabinUp);
            }
            return Json(new[] { CabinUp }.ToDataSourceResult(request, ModelState));
        }
        #endregion
        #region Supplier
        [Authorize]
        public ActionResult Suppliers_Read(int NetworkId, [DataSourceRequest] DataSourceRequest request)
        {
            SupplierBLL oBLL = new Models.BLL.SupplierBLL();
            return Json(oBLL.getSuppliersInNetwork(NetworkId).ToDataSourceResult(request));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize]
        public ActionResult Supplier_Update([DataSourceRequest] DataSourceRequest request, Supplier SupplierUp)
        {

NapoMVC/Views/Shared/Partial/_PartialHeaderSettings.cshtml
<div class="row">
    <div class="demo-section k-content wide col">
        <div id="toolbar"></div>
    </div>
</div>
<script>
            $(document).ready(function() {
                $("#toolbar").kendoToolBar({
                    items: [
                        { type: "button", text: "Home",url:"@Url.Action("Index","BackOffice",new { area=""})"},
                        {
                            type: "splitButton",
                            text: "Servizi",
                            menuButtons: [
                                { text: "Servizi", icon: "insert-up", url: "@Url.Action("Services","BackOffice")" },
                                { text: "Tipi Servizi", icon: "insert-middle" , url: "@Url.Action("ServiceTypes","BackOffice")"},
                            ]
                        },
                        {
                            type: "splitButton",
                            text: "Collaboratori",
                            menuButtons: [
                                { text: "Collaboratori", icon: "insert-up", url: "@Url.Action("Employees","BackOffice")" },
                                { text: "Tipi Collaboratori", icon: "insert-middle" , url: "@Url.Action("EmployeeTypes", "BackOffice")"},
                            ]
                        }
                    ]
                });

                $("#dropdown").kendoDropDownList({
                    optionLabel: "Paragraph",
                    dataTextField: "text",
                    dataValueField: "value",
                    dataSource: [
                        { text: "Heading 1", value: 1 },
                        { text: "Heading 2", value: 2 },
                        { text: "Heading 3", value: 3 },
                        { text: "Title", value: 4 },
                        { text: "Subtitle", value: 5 }
                    ]
                });
            });
</script>

NapoMVC/Views/Shared/Partial/_PartialModalTypeAdd.cshtml
@model int

<!--Sezione per modale tipi servizio-->
<div id="serviceTypeWindowModal" style="display:none">
    <div id="typeObject_ServiceType">
        <input type="hidden" id="Id_ServiceType" name="Id_ServiceType" value="0" />
        <input type="hidden" id="GUID_ServiceType" name="GUID_ServiceType" value="" />
        <input type="hidden" id="NetworkId_ServiceType" name="NetworkId_ServiceType" value="@Model" />
        Nome: <input type="text" id="Name_ServiceType" name="" value="" placeholder="Digita il nome..." /><br />
        Parent: <select id="ParentId_ServiceType" name="ParentId_ServiceType">
            <option value="0">
                ----
            </option>
        </select><br />
    </div>
    <button id="saveType" name="saveType" onclick="saveType_ServiceType()">Salva>></button>
    <script>
        function drawSelect_ServiceType() {
            $.ajax({
                url: '@Url.Action("getParentServices", "CRUD")',
                data: 'NetworkId=@Model',
                type: "POST",
                async: true,
                success: function (data) {
                    if (data) {
                        var _html = '';
                        var _sel = $("#ParentId_ServiceType");
                        _sel.empty();
                        _sel.append($("<option></option>")
                                .attr("value", 0).text('-----'));
                        for (var i = 0; i < data.length; i++) {
                            _sel.append($("<option></option>")
                                .attr("value", data[i].Id).text(data[i].Name));
                        }
                    }
                },
                fail: function () {
                    alert('Errore nella comunicazione: select');
                }
            });
        }
        function saveType_ServiceType() {
            var _o = new Object();
            var _id = $("#Id_ServiceType").val();
            var _guid = $("#GUID_ServiceType").val();
            var _network = '@Model';
            var _name = $("#Name_ServiceType").val();
            var _parent = $('#ParentId_ServiceType option:selected').val();
            _o.Name = _name;
            _o.Id = _id;
            _o.GUID = _guid;
            _o.NetworkId = _network;
            _o.ParentId = _parent;
            $.ajax({
                url: '@Url.Action("setServiceType", "CRUD")',
                data: 'JsonData=' + JSON.stringify(_o),
                type: "POST",
                async: true,
                success: function (data) {
                    if (data) {
                        if (data.Status.Status != 0)
                        {
                            alert(data.ResponseStatus.Error);
                        }
                    }
                },
                fail: function () {
                    alert('Errore nella comunicazione');
                }
            });
            $("#serviceTypeWindowModal").data("kendoWindow").close();
        }
        function openServiceTypeWindow()
        {
            drawSelect_ServiceType();
            $("#serviceTypeWindowModal").css("display", "block");
            var serviceTypeWindow = $("#serviceTypeWindowModal");
            //riempio con i valori trovati
            $("#Id_ServiceType").val('0');
            $("#GUID_ServiceType").val('');
            $("#Name_ServiceType").val('');
            $("#ParentId_ServiceType").val('');
            serviceTypeWindow.kendoWindow({
                width: 350,
                height: 200,
                title: "Gestione tipo: Nuovo",
                visible: false,
                actions: [
                    "Pin",
                    "Minimize",
                    "Maximize",
                    "Close"
                ],
                close: onCloseServiceTypeWindow
            }).data("kendoWindow").center().open();
        }
        function closeAllWindowModalType()
        {
            if ($("#serviceTypeWindowModal").data("kendoWindow")!=null)
                $("#serviceTypeWindowModal").data("kendoWindow").close();
        }
    </script>

</div>
<!--Fine sezione modale tipi servizio-->